Product_App/Product_App/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', 'django.contrib.auth.views.login'),
    url(r'^products/', include('product.urls',namespace='product')),
    url(r'^logout/', 'django.contrib.auth.views.logout'),
    #url(r'^admin/products/', include('product.urls',namespace='product')),
]

Product_App/product/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.products, name='products'),
    url(r'^(?P<slug>\w+)/$', views.detail, name='detail'),
    url(r'^(?P<slug>\w+)/vote/$', views.vote, name='vote'),
]

Product_App/product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime
from django.core.urlresolvers import reverse

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    price = models.FloatField(default=0.0)
    rate = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.created_at <= now

    was_published_recently.admin_order_field = 'created_at'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('product:detail', args=[str(self.slug)])

class Post(models.Model):
    title = models.CharField(max_length=60)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User,default=1)
    product = models.ForeignKey(Product,default=1)

    def __str__(self):
        return self.title

class Vote(models.Model):
    product = models.ForeignKey(Product,default=1)
    author = models.ForeignKey(User,default=1)
    rate = models.BooleanField('Liked')

Product_App/product/forms.py
__author__ = 'krop'
from django.forms import ModelForm, Textarea, CharField



from .models import Post

class CommentForm(ModelForm):
    title = CharField(max_length=30,min_length=3, required=True)
    body = CharField(max_length=300,min_length=5, required=True,widget = Textarea(attrs={'cols': 24, 'rows': 5}),label='Enter the message')
    class Meta:
        model = Post
        fields = ['title', 'body']

Product_App/product/views.py
from django.shortcuts import get_object_or_404, render
from django.template import RequestContext
from .models import Product, Post, Vote
from django.views import generic
from django import forms
from django.db import connection
from product.forms import CommentForm
import sys
from datetime import datetime

# Create your views here.
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.core.context_processors import csrf
from django.http import HttpResponseRedirect, HttpResponse
from django.conf import settings
from django.shortcuts import redirect
from django.core.paginator import Paginator, InvalidPage, EmptyPage

from django.contrib.auth import logout

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def login_view(request):
    messages.add_message(request, 50, 'A serious error occurred.')
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            if not request.user.is_authenticated():
                #return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            raise forms.ValidationError("Sorry, that login was invalid. Please try again.")
            # Return a '        #return ('detail',(),{'slug':str(self.slug)})
        #print(reverse('detail', args=[str(self.slug)]))disabled account' error message
    else:
        raise forms.ValidationError("Sorry, that login was invalid. Please try again.")
        # Return an 'invalid login' error message.

class IndexView(generic.ListView):
    template_name = 'product/list.html'
    context_object_name = 'product_list'


    def get_queryset(self):
        """Return the last five published questions."""
        return Product.objects.order_by('created_at')
def products(request):
    product_list = Product.objects.order_by('created_at')
    sort = request.GET.get('sort')
    #products = Product.objects.all()
    print('hello')
    if sort is not None:
        product_list = product_list.order_by(sort)

        if headers[sort] == "des":
            product_list.reverse()
            headers[sort] = "asc"
        else:
            headers[sort] = "des"
    return render(request, 'product/list.html', {'product_list':product_list})

def detail(request,slug):
    product_list = Product.objects.order_by('created_at')[:5]
    product = get_object_or_404(Product,slug=slug)
    formset = CommentForm(request.POST or None)
    if formset.is_valid():
        comment = formset.save(commit=False)
        comment.product = product
        comment.author = request.user
        comment.save()
        return redirect(request.path)

    try:
        ldc = str(product.post_set.last().created)[:10].split("-")
        ldc = [int(i) for i in ldc]
        comments = product.post_set.filter(created__year=ldc[0],created__month=ldc[1],created__day=ldc[2])
        more_comments = product.post_set.exclude(created__year=ldc[0],created__month=ldc[1],created__day=ldc[2])
        more_comments.order_by('created_at')
    #print(comments,comments2)
        context = {'product_list':product_list,'product':product,'comments':comments,'more_comments':more_comments,'formset': formset}
        context.update(csrf(request))
        return render(request, 'product/detail.html', context)
    except:
        context = {'product_list':product_list,'product':product,'formset': formset}
        context.update(csrf(request))
        return render(request, 'product/detail.html', context)


def vote(request, slug):
    p = get_object_or_404(Product, slug=slug)
    product_id= Product.objects.get(slug=slug).pk
    try:
        if request.user.is_authenticated():
            if Vote.objects.filter(rate=True, author_id=request.user.id,product_id=product_id).count() >0:
                vote_update(False,product_id,request.user.id)
                p.rate -= 1
                p.save()

            elif Vote.objects.filter(rate=False, author_id=request.user.id,product_id=product_id).count() >0:
                vote_update(True,product_id,request.user.id)
                p.rate += 1
                p.save()
                messages.add_message(request, messages.SUCCESS, 'Voted',fail_silently=True)
            elif Vote.objects.filter(author_id=request.user.id,product_id=product_id).count()==0:
                voted = Vote(rate=True,product_id=product_id,author_id=request.user.id)
                voted.save()
                p.rate += 1
                p.save()
                messages.add_message(request, messages.SUCCESS, 'Voted',fail_silently=True)

        else:
            return HttpResponseRedirect(reverse('django.contrib.auth.views.login'))
        
    except (KeyError, Product.DoesNotExist):
        # Redisplay the product.post_set.all()question voting form.
        return render(request, 'product/detail.html', {
            'product': p,
            'error_message': "Pleasure login.",
        })




    return HttpResponseRedirect(reverse('product:detail', args=(p.slug,)))

def vote_update(rate,product_id,author_id):
    cursor = connection.cursor()
    cursor.execute('UPDATE product_vote SET rate=%s WHERE product_id= %s and author_id= %s',[rate,product_id,author_id])

headers = {'name':'asc',
         'price':'asc',
         'rate':'asc',}
def table_view(request):
    sort = request.GET.get('sort')
    print('lil')
    products = Product.objects.all()
    if sort is not None:
        products = products.order_by(sort)

        if headers[sort] == "des":
            products.reverse()
            headers[sort] = "asc"
        else:
            headers[sort] = "des"
            products.order_by(sort)

    return HttpResponseRedirect(reverse('product',{'product_list':products}))

Product_App/product/templates/product/detail.html
{% extends "base.html" %}
{% block title %}{{ product.name }}{% endblock %}
{% block content %}
    <div class="nav">
        {% if product_list %}
            {% for p in product_list %}
                <a href="{% url 'product:detail' p.slug %}">{{ p.name }}</a><br>
            {% endfor %}
        {% else %}
            <p>No Products</p>
        {% endif %}

    </div>
    <div class="detail">
        <h1>{{ product.name }}</h1>

        <h2>{{ product.price }}$</h2>

        <p>{{ product.description }}</p>

        <p>
            <small>Product added: {{ product.created_at }}</small>
        <form action="{% url 'product:vote' product.slug %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="Vote" name="vote">
            <label for="vote">{{ product.rate }}</label><br>
        </form>
        </p>
        <hr>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        {% if comments %}
            <p>Comments:</p>
            <ul>{% for comment in comments reversed %}
                <div class="comment">
                    <div class="time">
                        <small> Comment: <b>{{ comment.author }}</b> | {{ comment.created }}</small>
                    </div>
                    <hr>
                    <div class="body"><i>{{ comment.body|linebreaks }}</i></div>
                </div>
                <br>
            {% endfor %}
            </ul>
            {% if more_comments.count > 0 %}
                <div id="spoiler" style="display:none">
                    <ul>{% for comment in more_comments reversed %}
                        <div class="comment">
                            <div class="time">
                                <small> Comment: <b>{{ comment.author }}</b> | {{ comment.created }}</small>
                            </div>
                            <hr>
                            <div class="body"><i>{{ comment.body|linebreaks }}</i></div>
                        </div>
                        <br>
                    {% endfor %}
                    </ul>
                </div>
                <button title="Click to show/hide content" type="button"
                        onclick="if(document.getElementById('spoiler') .style.display=='none') {document.getElementById('spoiler') .style.display=''}else{document.getElementById('spoiler') .style.display='none'}">
                    Show comments
                </button>
            {% endif %}
        {% endif %}
        <div id="addc">Add a comment</div>
        <form action="" method="POST">
            {% csrf_token %}
            <ul>
                <li style="">{{ formset.title.label }}</li>
            <li>{{ formset.title }} {{ formset.title.errors }}</li>
            <li>{{ formset.body.label }}</li>
            <li>{{ formset.body }}{{ formset.body.errors }}</li></ul>

            <input type="submit" name="submit" value="Submit"/>
        </form>
    </div>
{% endblock %}

Product_App/product/templates/product/list.html
{% extends "base.html" %}
{% block title %}Product list{% endblock %}
{% block content %}
    <div class="detil">
        {% if product_list %}
            <table id="example" class="display" width="100%" cellspacing="0" style="width: 100%">
                <thead>
                <tr>
                    <td>Name</td>
                    <td>Description</td>
                    <td>Price</td>
                    <td>Likes</td>
                </tr>
                </thead>
                <tfoot>
                <td>Name</td>
                <td>Description</td>
                <td>Price</td>
                <td>Likes</td>
                </tfoot>
                <tbody>
                {% for p in product_list %}

                    <tr>
                        <td data-search="{{ p.name }}"><a href="{% url 'product:detail' p.slug %}">{{ p.name }}</a></td>
                        <td>{{ p.description }}</td>
                        <td>{{ p.price }}$</td>
                        <td>{{ p.rate }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No Products</p>
        {% endif %}
    </div>
    <script>
        $(document).ready(function () {
            $('#example').DataTable();
        });
    </script>
{% endblock %}

Product_App/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <link href="{% static "css/style.css" %}" rel="stylesheet" media="screen"/>
    <link href="{% static "css/jquery.dataTables.css" %}" rel="stylesheet" media="screen"/>
    <script type="text/javascript" src="{% static "js/jquery-1.11.1.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/jquery.dataTables.min.js" %}"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="page-wrapper">
    <div class="log">
        {% if user.username %}
            <form action="{% url 'django.contrib.auth.views.logout' %}?next={{request.path}}" method="POST">
                {% csrf_token %}
                <input type="submit" value="Logout" name="logout">
                <label for="logout" text-align='left' float='left'>
                    <small>Login as: {{ user.username }}</small>
                </label><br>
            </form></p>
        {% else %}
            <form action="{% url 'django.contrib.auth.views.login' %}?next={{request.path}}" method="POST">
                {% csrf_token %}
                <input type="submit" value="Login" name="login">
                <label for="login" text-align='left' float='left'>
                    <small>Login as: Anon</small>
                </label><br>
            </form></p>
        {% endif %}
    </div>
    <div class="header">
        <h1><a href="{% url 'product:products' %}"> Products</a></h1>
    </div>
    {% block content %}{% endblock %}
    <div class="page-buffer"></div>
</div>
<div class="footer">
    Copyright © Krop
</div>
</body>
</html>